import { loadLatestSnapshot } from "../../../lib/market-turso";
import { dashboardData } from "../data";
import styles from "../page.module.css";

export const dynamic = "force-dynamic";

export default async function LaborMarketPage() {
  const d = await loadLatestSnapshot(dashboardData);
  return <main className={styles.page}>
    <header className={styles.top}><div><span className={styles.topKicker}>Labor market</span><h1 className={styles.title}>Weak, improving modestly</h1><p className={styles.dek}>Posting demand, actual-worker data and NYC signals stay separate so a hiring-cycle decline is not automatically attributed to AI.</p></div><dl className={styles.stamp}><div><dt>Indeed SWE</dt><dd>{d.trends.swe.current}</dd></div><div><dt>Overall</dt><dd>{d.trends.overall.current}</dd></div></dl></header>
    <nav className={styles.sectionNav}><a href="/ai-dashboard">Overview</a><a href="/ai-dashboard/personal-risk">Personal risk</a><a href="/ai-dashboard/labor-market">Labor market</a><a href="/ai-dashboard/ai-replacement">AI replacement</a><a href="/ai-dashboard/career-response">Career response</a></nav>
    <section className={styles.readout}><div><span>Answer</span><h2>SWE hiring remains structurally weak, but the latest repeatable series is moving up rather than down.</h2><p>The two-week Indeed move is +{d.trends.swe.twoWeekPct}%; the four-week move is +{d.trends.swe.fourWeekPct}%. The gap versus overall U.S. postings narrowed, but remains large.</p></div></section>
    <section className={styles.section}><header className={styles.sectionHead}><div><span>01</span><h2>Indeed / FRED</h2></div><p>Stable indexed series, February 2020 = 100.</p></header><div className={styles.metricGrid}>
      <article className={styles.down}><span>Software development</span><strong>{d.trends.swe.current}</strong><p>As of {d.trends.swe.asOf}</p></article>
      <article className={styles.neutral}><span>Overall U.S. postings</span><strong>{d.trends.overall.current}</strong><p>As of {d.trends.overall.asOf}</p></article>
      <article className={styles.down}><span>SWE gap vs overall</span><strong>{d.trends.relativeGapPoints.toFixed(2)} pts</strong><p>{d.trends.relativeGapPct.toFixed(2)}% relative</p></article>
      <article className={styles.up}><span>SWE · 2 weeks</span><strong>+{d.trends.swe.twoWeekPct}%</strong><p>Improving</p></article>
      <article className={styles.up}><span>SWE · 4 weeks</span><strong>+{d.trends.swe.fourWeekPct}%</strong><p>Positive, no structural break yet</p></article>
    </div></section>
    <section className={styles.section}><header className={styles.sectionHead}><div><span>02</span><h2>Tech-company and NYC demand</h2></div><p>TrueUp and LinkedIn are separate universes.</p></header><div className={styles.splitTables}><article><h3>TrueUp categories · {d.trueup.asOf}</h3><table className={styles.compactTable}><tbody>{d.trueup.categories.slice(0,6).map(x=><tr key={x.name}><th>{x.name}</th><td>{x.jobs.toLocaleString()}</td><td>+{x.trendPct}%</td></tr>)}</tbody></table></article><article><h3>LinkedIn NYC</h3><table className={styles.compactTable}><tbody><tr><th>Last verified stable query</th><td>{d.linkedin.countLabel}</td><td>{d.linkedin.asOf}</td></tr><tr><th>Current refresh</th><td>Unavailable</td><td>Exact query count not reproducible</td></tr><tr><th>Direction</th><td>Not classified</td><td>Missing ≠ flat</td></tr></tbody></table><p className={styles.detailNote}>{d.linkedin.note}</p></article></div></section>
    <section className={styles.section}><header className={styles.sectionHead}><div><span>03</span><h2>Actual workers</h2></div><p>Revelio released August broad-market data on {d.revelio.releaseDate}; the prior comparable SOC15 occupation slice is retained separately.</p></header><div className={styles.tableWrap}><table className={styles.dataTable}><thead><tr><th>Measure</th><th>Current</th><th>MoM</th><th>YoY</th></tr></thead><tbody><tr><td>SOC15 employment · retained occupational slice</td><td>{d.revelio.employmentThousands.toLocaleString()}k</td><td>{d.revelio.employmentChangeMomThousands}k</td><td>{d.revelio.employmentChangeYoyThousands}k</td></tr><tr><td>SOC15 openings · retained occupational slice</td><td>{d.revelio.jobOpenings.toLocaleString()}</td><td>+{d.revelio.jobOpeningsMomPct}%</td><td>+{d.revelio.jobOpeningsYoyPct}%</td></tr><tr><td>Broad U.S. employment · August change</td><td>+{d.revelio.broadEmploymentChangeThousands}k</td><td>—</td><td>—</td></tr><tr><td>Broad active postings · August</td><td>—</td><td>{d.revelio.broadOpeningsMomPct}%</td><td>—</td></tr><tr><td>Broad hiring rate · August</td><td>{d.revelio.broadHiringRatePct}%</td><td>—</td><td>—</td></tr></tbody></table></div><p className={styles.detailNote}>{d.revelio.note}</p></section>
    <section className={styles.section}><header className={styles.sectionHead}><div><span>04</span><h2>Causality</h2></div><p>Current evidence fits weak white-collar demand plus AI-driven task and skill restructuring better than broad experienced-SWE replacement.</p></header><div className={styles.evidenceList}><article className={styles.warning}><div><span>Prior comparable AI-exposure demand estimate</span><strong>{d.aiLaborTracker.exposedRoleDemandChangePct}%</strong></div><p>Broad exposure measure retained for context; not a current experienced-SWE estimate.</p></article><article className={styles.up}><div><span>AI-adopting firm headcount</span><strong>+{d.aiLaborTracker.adoptingFirmHeadcountGrowthPct}%</strong></div><p>Senior headcount growth is +{d.aiLaborTracker.adoptingFirmSeniorGrowthPct}% versus +{d.aiLaborTracker.adoptingFirmJuniorGrowthPct}% for junior workers.</p></article><article className={styles.neutral}><div><span>Change within jobs</span><strong>{d.aiLaborTracker.withinJobActivityChangePct}%</strong></div><p>Supports restructuring of job content as the dominant measured mechanism.</p></article></div></section>
  </main>;
}
