export const dashboardData = {
  updatedAt: "2026-08-14",
  nextRefresh: "2026-08-28",
  cadence: "Every 2 weeks",
  currentRead:
    "The current evidence looks more like a restructuring of software engineering than broad replacement. Entry-level employment is under pressure, but software demand has rebounded from the 2023 trough and frontier agents still show major long-horizon reliability limits.",
  metrics: [
    {
      label: "Indeed/FRED SWE hiring",
      value: "74.56",
      note: "Jul 10, 2026 · Feb 2020 = 100",
      tone: "negative",
    },
    {
      label: "TrueUp software jobs",
      value: "54,747",
      note: "Jun 30, 2026 · +34.1% on TrueUp trend measure",
      tone: "positive",
    },
    {
      label: "LinkedIn NY SWE",
      value: "4,000+",
      note: "Public New York search · snapshot Aug 14",
      tone: "neutral",
    },
    {
      label: "Early-career SWE",
      value: "≈ -20%",
      note: "Age 22–25 employment vs. 2024 · Stanford",
      tone: "negative",
    },
    {
      label: "DeepSWE frontier",
      value: "74%",
      note: "Claude Opus 5 · leaderboard updated Aug 13",
      tone: "neutral",
    },
    {
      label: "METR 50% horizon",
      value: "~12 h",
      note: "Public frontier · Feb–Mar 2026 · high uncertainty",
      tone: "neutral",
    },
  ],
  trueup: {
    asOf: "2026-06-30",
    totalTechJobs: 262300,
    categoryTotal: 216625,
    softwareJobs: 54747,
    softwareTrendPct: 34.1,
    categories: [
      { name: "Data Science & ML", jobs: 9075, trendPct: 90.1 },
      { name: "Sales Engineering", jobs: 6231, trendPct: 66.7 },
      { name: "Business Ops / Program Mgmt", jobs: 16555, trendPct: 43.6 },
      { name: "Software Engineering", jobs: 54747, trendPct: 34.1 },
      { name: "Research", jobs: 1695, trendPct: 28.4 },
      { name: "Product Management", jobs: 5752, trendPct: 27.2 },
      { name: "IT & Business Systems", jobs: 8312, trendPct: 22.0 },
      { name: "Hardware Engineering", jobs: 4004, trendPct: 14.4 },
    ],
    source: "https://www.trueup.io/job-category-trends",
    chartSource: "https://trueup.io/trends",
    methodology: "TrueUp tracks open jobs at startups and large tech companies; it is not the entire U.S. labor market.",
  },
  linkedin: {
    asOf: "2026-08-14",
    query: "Software Engineer · New York",
    countLabel: "4,000+",
    source: "https://www.linkedin.com/jobs/search/?geoId=105080838&keywords=software%20engineer&location=New%20York%2C%20United%20States",
    note: "LinkedIn rounds public result counts and search indexing can lag. We track the same query every cycle for directional movement.",
  },
  revelio: {
    asOf: "2026-07",
    releaseDate: "2026-08-06",
    occupation: "Computer and Mathematical (SOC 15)",
    employmentThousands: 10021.5,
    employmentChangeMomThousands: -0.6,
    employmentChangeYoyThousands: -39.9,
    jobOpenings: 1686687,
    jobOpeningsMomPct: 2.3,
    jobOpeningsYoyPct: 22.8,
    hiringRatePct: 26.7,
    hiringChangeMomPp: 0.4,
    hiringChangeYoyPp: -0.7,
    attritionRatePct: 26.7,
    attritionChangeMomPp: -0.7,
    attritionChangeYoyPp: -1.9,
    newPostingSalary: 124266,
    salaryChangeMomPct: -0.1685,
    salaryChangeYoyPct: 4.4389,
    source: "https://www.reveliolabs.com/public-labor-statistics",
    note: "Public monthly occupation-level baseline. SOC 15 is broader than software engineering and is not a YOE-specific series.",
  },
  marketDetails: {
    overallPostings: { value: 102.09, asOf: "2026-07-24" },
    seniority: {
      seniorSharePct: 69.3,
      midChangePct: -6.7,
      seniorChangePct: 13.5,
      comparison: "Change since January 2025",
      source: "Indeed Hiring Lab seniority analysis",
    },
    linkedinSeniority: {
      entry: 525,
      associate: 159,
      midSenior: 3490,
      anyTime: 4978,
      pastMonth: 3986,
      pastWeek: 1489,
      pastDay: 370,
      asOf: "2026-08-14",
    },
    bls: {
      growthPct: 15.8,
      jobsAdded: 267700,
      period: "2024–2034",
      source: "https://www.bls.gov/opub/ted/2026/artificial-intelligence-information-technology-and-employment-2024-34.htm",
    },
  },
  benchmarks: [
    { model: "Claude Opus 5", score: 74, cost: "$11.84", note: "DeepSWE v1.1" },
    { model: "GPT-5.6 Sol", score: 73, cost: "$8.39", note: "DeepSWE v1.1" },
    { model: "Claude Fable 5", score: 70, cost: "$21.63", note: "DeepSWE v1.1" },
    { model: "Kimi K3", score: 69, cost: "—", note: "DeepSWE v1.1" },
    { model: "GPT-5.6 Luna", score: 67, cost: "—", note: "DeepSWE v1.1" },
    { model: "GPT-5.5", score: 67, cost: "—", note: "DeepSWE v1.1" },
    { model: "Claude Opus 4.8", score: 59, cost: "—", note: "DeepSWE v1.1" },
    { model: "Claude Sonnet 5", score: 54, cost: "—", note: "DeepSWE v1.1" },
  ],
  signals: [
    {
      signal: "Early-career SWE employment",
      reading: "Nearly -20% vs. 2024",
      direction: "Negative",
      interpretation: "Strongest clearly observed labor-market warning; the damage is concentrated near the bottom of the career ladder.",
      source: "https://hai.stanford.edu/ai-index/2026-ai-index-report/economy",
    },
    {
      signal: "Experienced-worker employment",
      reading: "No comparable decline",
      direction: "Stable",
      interpretation: "Current evidence does not show broad displacement of experienced software workers.",
      source: "https://digitaleconomy.stanford.edu/project/indicators/canaries-dashboard/",
    },
    {
      signal: "Automation vs augmentation",
      reading: "Higher automation share correlates with weaker employment",
      direction: "Watch",
      interpretation: "How AI is deployed appears more informative than exposure alone.",
      source: "https://digitaleconomy.stanford.edu/project/indicators/canaries-dashboard/",
    },
    {
      signal: "AI agents in business",
      reading: "Single-digit deployment in nearly all functions",
      direction: "Early",
      interpretation: "Economic diffusion has substantial room to run even without another model breakthrough.",
      source: "https://hai.stanford.edu/ai-index/2026-ai-index-report/economy",
    },
    {
      signal: "METR public frontier",
      reading: "~12h 50% task horizon",
      direction: "Improving",
      interpretation: "Strong progress, but not equivalent to autonomous multi-day production engineering.",
      source: "https://metr.org/blog/2026-05-19-frontier-risk-report/",
    },
    {
      signal: "Benchmark reliability",
      reading: "~30% of SWE-Bench Pro tasks estimated broken",
      direction: "Warning",
      interpretation: "Headline benchmark gains should not be treated as direct labor-replacement evidence.",
      source: "https://openai.com/index/separating-signal-from-noise-coding-evaluations/",
    },
  ],
  pivotRadar: [
    {
      area: "AI / ML systems infrastructure",
      status: "Rising",
      evidence: "TrueUp DS/ML +90.1%; current NYC postings include AI inference, ML systems and AI security infrastructure.",
      fit: "High",
      track: "NYC AI infra / ML systems posting count, seniority, compensation and employer breadth.",
    },
    {
      area: "Sales engineering / Forward Deployed Engineering",
      status: "Rising",
      evidence: "TrueUp Sales Engineering +66.7%; AI adoption creates demand for engineers who can deploy systems into real businesses.",
      fit: "Medium-high",
      track: "NYC FDE, Solutions Engineer and Sales Engineer counts plus compensation and technical depth.",
    },
    {
      area: "Trading / market infrastructure",
      status: "Strong niche",
      evidence: "Current NYC search surfaces quant-dev, systematic market-making, eTrading and C++ quant-infrastructure roles across banks, Bloomberg and trading firms.",
      fit: "High",
      track: "Quant dev, eTrading, market data, execution and trading-systems openings by company and skill.",
    },
    {
      area: "Distributed systems / cloud platform",
      status: "Durable",
      evidence: "Current NYC postings include distributed workflow engines, cloud platform, connectivity and backend infrastructure roles.",
      fit: "High",
      track: "Distributed systems, platform, SRE, cloud infra and connectivity openings versus generic application SWE.",
    },
    {
      area: "Hardware / AI compute infrastructure",
      status: "Watch",
      evidence: "TrueUp hardware engineering is positive and AI infrastructure investment can create software-adjacent systems work.",
      fit: "Medium",
      track: "AI compute, networking, data-center software, compilers and systems postings in NYC/remote US.",
    },
  ],
  jobs: [
    { category: "Core SWE", company: "Google", role: "Software Engineer, Early Career, Campus", comp: "$123k–$174k", location: "New York, NY", url: "https://to.indeed.com/aa6s2phc7dtv" },
    { category: "Systems", company: "Bloomberg", role: "Senior Software Engineer - Integration Runtime", comp: "$160k–$240k", location: "New York, NY", url: "https://click.appcast.io/t/Kd3-IwGGbQltjHFeuijnsMnEYvmYMdD-TVIR6Go5sEvUT8QXugmYKCPj9Zc2q5TsStj6YT8I5fZg1JbfZGfhvw==?sar_id=29cx42r7&jpos=10" },
    { category: "Systems", company: "Salesforce", role: "Distributed Systems Software Engineer SMTS/LMTS", comp: "$148.5k–$223.9k", location: "New York, NY", url: "https://to.indeed.com/aaqyzydyr7fx" },
    { category: "Backend", company: "Plaid", role: "Software Engineer, Backend", comp: "$176.4k–$226.8k", location: "New York, NY", url: "https://to.indeed.com/aawtdxhftk6m" },
    { category: "AI infrastructure", company: "Amazon", role: "Software Engineer, AI Security", comp: "Not listed", location: "New York, NY", url: "https://click.appcast.io/t/TQJQ-SByNfPdgUpXyas60tEzERZV2DK4TsmrHwI-SVdq6boEr5rm4KDSKCHwkoeoVn_vPqJrSLdVbfoFK2_vmQ==?sar_id=29cx42r7&jpos=4" },
    { category: "Quant", company: "Point72 / Cubist", role: "Quantitative Analyst / Software Developer", comp: "$200k–$300k", location: "New York, NY", url: "https://to.indeed.com/aarc8bttk8y2" },
    { category: "eTrading", company: "RBC", role: "Rates Algo Developer, Associate", comp: "$165k–$200k", location: "New York, NY", url: "https://to.indeed.com/aaljrtqvvwdv" },
    { category: "Quant", company: "Goldman Sachs", role: "Quantitative Developer - Systematic Market Making", comp: "$130k–$250k", location: "New York, NY", url: "https://to.indeed.com/aacdqcgyf4v7" },
    { category: "Quant", company: "IMC", role: "Quantitative Developer", comp: "$200k–$225k", location: "New York, NY", url: "https://to.indeed.com/aajj8tgx9p88" },
    { category: "Quant infra", company: "Bloomberg", role: "Quantitative Developer - C++ Infrastructure for Quant Analytics", comp: "$160k–$250k", location: "New York, NY", url: "https://click.appcast.io/t/nr-MOzUqaimWYsRJ7loX2e4MIgbRoerxSuxKrPXRM8bm6zqKIFYYCHAcKzXqwW2hTHOVwWtgrIjDC7b91jm87g==?sar_id=29cx43jt&jpos=0" },
  ],
  history: [
    {
      date: "2026-08-14",
      sweHiring: 74.56,
      hiringDate: "2026-07-10",
      trueupSoftwareJobs: 54747,
      trueupDate: "2026-06-30",
      linkedinNycSwe: "4,000+",
      earlyCareerChange: "≈ -20%",
      deepSweBest: 74,
      deepSweLeader: "Claude Opus 5",
      metrHorizon: "~12h",
    },
  ],
  sources: [
    ["SWE hiring", "FRED / Indeed", "https://fred.stlouisfed.org/series/IHLIDXUSTPSOFTDEVE"],
    ["Tech/SWE openings", "TrueUp", "https://www.trueup.io/job-category-trends"],
    ["Tech hiring graphics", "TrueUp Trends", "https://trueup.io/trends"],
    ["NY software jobs", "LinkedIn", "https://www.linkedin.com/jobs/search/?geoId=105080838&keywords=software%20engineer&location=New%20York%2C%20United%20States"],
    ["Labor displacement", "Stanford Digital Economy Lab", "https://digitaleconomy.stanford.edu/project/indicators/canaries-dashboard/"],
    ["Economy / adoption", "Stanford AI Index", "https://hai.stanford.edu/ai-index/2026-ai-index-report/economy"],
    ["Autonomous task horizon", "METR", "https://metr.org/time-horizons/"],
    ["Hard coding benchmark", "DeepSWE", "https://deepswe.datacurve.ai/"],
    ["Agent benchmark", "Terminal-Bench 2.1", "https://www.tbench.ai/leaderboard/terminal-bench/2.1"],
  ],
} as const;

export const sourceArchitecture = [
  {
    source: "Lightcast Job Posting Analytics",
    role: "Optional high-priority granular postings layer",
    availability: "Conditional — public/free-access data only unless credentials become available",
    confidence: "Pending access; strong methodology, no dashboard microdata loaded",
    use: "Deduplicated postings, minimum YOE, skills, salary, employer breadth, freshness, and persistence.",
    limit: "Do not display Lightcast values from product documentation or public reports as if they were licensed microdata.",
    url: "https://docs.lightcast.io/data/docs/job-posting-analytics-jpa-methodology",
  },
  {
    source: "Revelio Public Labor Statistics",
    role: "Actual-worker, hiring, attrition, openings, and salary layer",
    availability: "Active — July 2026 public occupation baseline stored",
    confidence: "Medium–high; public monthly series",
    use: "Independent worker-flow confirmation by occupation, sector, and state.",
    limit: "SOC 15 is broader than SWE and is not experience-specific; keep it separate from posting counts.",
    url: "https://www.reveliolabs.com/public-labor-statistics",
  },
  {
    source: "BLS CPS / OEWS",
    role: "Slower structural employment and compensation confirmation",
    availability: "Active public source — used on its release cadence",
    confidence: "High within survey and sampling limits",
    use: "CPS employment/unemployment context and OEWS occupation- and metro-level employment and wages.",
    limit: "Background confirmation, not the biweekly headline and not a rapid AI-discontinuity detector.",
    url: "https://www.bls.gov/cps/",
  },
  {
    source: "SEC filings, earnings, and company disclosures",
    role: "Experienced-SWE AI-substitution evidence gate",
    availability: "Event-driven public review — no qualifying observation currently stored",
    confidence: "High only when headcount, output, and AI attribution are explicit",
    use: "Experienced backfills, engineering headcount, output per engineer, and direct AI attribution.",
    limit: "A productivity quote or coding benchmark alone is not replacement evidence.",
    url: "https://www.sec.gov/edgar/search/",
  },
  {
    source: "New York WARN notices",
    role: "NYC layoff-shock context",
    availability: "Active public watch — no NYC SWE-specific observation currently stored",
    confidence: "High for covered layoff events; low for occupation or AI specificity",
    use: "Test whether a sharp NYC move is concentrated in a few large announced layoffs.",
    limit: "WARN coverage is incomplete and does not establish SWE composition or AI causality.",
    url: "https://dol.ny.gov/warn-dashboard",
  },
] as const;

export const longitudinalMethod = [
  "Append each dated observation; never overwrite earlier snapshots.",
  "Show 2-week, 4-week, 12-week, and year-over-year movement only after enough observations exist.",
  "Treat missing or inaccessible data as unavailable, never as zero or stable.",
  "Keep NYC separate from national data and literal YOE separate from platform seniority labels.",
  "Keep actual worker outcomes and company substitution evidence separate from AI capability benchmarks.",
] as const;
