export const dashboardData = {
  updatedAt: "2026-09-11",
  nextRefresh: "2026-09-25",
  cadence: "Every 2 weeks",
  currentRead: "SWE hiring is still structurally weak, but the latest repeatable series improved modestly rather than deteriorating. The best current labor evidence still points to AI changing job content and raising productivity more than broadly replacing experienced engineers. For a competent engineer around 5 YOE, risk remains Low–Moderate: specialization and experience-depth requirements are rising, but there is still no evidence of a new mid-career employment cliff.",
  overview: {
    personalRisk: "Low–Moderate",
    personalRiskTrend: "Stable",
    personalRiskConfidence: "Medium",
    hiring: "Weak, improving modestly",
    hiringTrend: "Rising from depressed base",
    aiReplacement: "Yellow / watch",
    aiReplacementTrend: "Stable yellow",
    midLevel: "Weak / specialization rising",
    senior: "Relatively stronger",
    nycDemand: "No verified break; exact longitudinal LinkedIn count was not reproducibly exposed this refresh",
    pivot: "No pivot signal",
    pivotDistance: "Three of four pivot gates remain unmet. AI-driven productivity/substitution pressure is real, but broad experienced-SWE displacement and reliable multi-day autonomous ownership are not established.",
    changed: [
      "Indeed/FRED software-development postings rose from 74.57 to 76.12 over the latest comparable two-week interval (+2.1%), while overall postings rose only about 0.5%; the SWE gap narrowed but remains large.",
      "Revelio's August AI tracker says 87% of measured work-content change is occurring within jobs; AI-adopting firms show much stronger senior than junior headcount growth (+32% versus +6%).",
      "Tech hiring is becoming more specialized: Revelio's 75M-posting analysis says average skill count fell from about 30 to 21 while average required experience per skill rose from roughly 4.6 to 4.8 years since 2024.",
      "Wipro says AI has freed capacity equivalent to about 20,000 workers, but it reports redeploying that capacity rather than cutting those workers and is expanding forward-deployed engineering.",
      "Frontier agent capability improved in breadth: GPT-6 Astra and Gemini 3.8 Flash joined Claude Opus 5 at the 74% DeepSWE ceiling, while GPT-6 Astra reached 87.4% on Terminal-Bench 2.1. This raises capability pressure but does not establish reliable multi-day production ownership.",
    ],
  },
  metrics: [
    { label: "Indeed/FRED SWE hiring", value: "76.12", note: "Sep 4, 2026 · Feb 2020 = 100", tone: "negative" },
    { label: "TrueUp software jobs", value: "54,747", note: "Aug 31, 2026 · +34.1% on TrueUp trend measure", tone: "positive" },
    { label: "LinkedIn NY SWE", value: "4,000+ last verified", note: "Exact stable query last reproducibly observed Aug 28", tone: "neutral" },
    { label: "Early-career AI gap", value: "-19%", note: "Ages 22–25 in highly AI-exposed occupations · Stanford revised analysis", tone: "negative" },
    { label: "DeepSWE frontier", value: "74%", note: "Three-way frontier tie · leaderboard Sep 3", tone: "neutral" },
    { label: "METR 50% horizon", value: "~12 h", note: "Latest public frontier estimate · high uncertainty above 16h", tone: "neutral" },
  ],
  trends: {
    swe: {
      current: 76.12,
      asOf: "2026-09-04",
      twoWeekPct: 2.08,
      fourWeekPct: 3.34,
      twelveWeekPct: null,
      yoyPct: null,
      direction: "Rising",
      velocity: "Improving",
      structuralBreak: false,
      note: "The latest movement is positive, but it is not large enough to erase the persistent post-2022 weakness or qualify as a structural break.",
    },
    overall: {
      current: 102.41,
      asOf: "2026-09-04",
      twoWeekPct: 0.49,
      fourWeekPct: null,
      twelveWeekPct: null,
      yoyPct: null,
      direction: "Flat to slightly rising",
      velocity: "Stable",
    },
    relativeGapPoints: -26.29,
    relativeGapPct: -25.67,
  },
  trueup: {
    asOf: "2026-08-31",
    totalTechJobs: 262300,
    categoryTotal: 216625,
    softwareJobs: 54747,
    softwareTrendPct: 34.1,
    categories: [
      { name: "Data Science & ML", jobs: 9075, trendPct: 90.1 },
      { name: "Sales Engineering", jobs: 6231, trendPct: 66.7 },
      { name: "Business Ops / Program Mgmt", jobs: 16555, trendPct: 43.6 },
      { name: "Software Engineering", jobs: 54747, trendPct: 34.1 },
      { name: "Research", jobs: 1695, trendPct: 28.4 },
      { name: "Product Management", jobs: 5752, trendPct: 27.2 },
      { name: "IT & Business Systems", jobs: 8312, trendPct: 22.0 },
      { name: "Hardware Engineering", jobs: 4004, trendPct: 14.4 },
    ],
    softwareSubcategories: [
      { name: "Machine Learning", jobs: 4153, trendPct: 74.2 },
      { name: "Site Reliability Engineering", jobs: 1712, trendPct: 53.3 },
      { name: "Data", jobs: 4095, trendPct: 51.2 },
      { name: "Networking", jobs: 1028, trendPct: 40.4 },
      { name: "Generalist", jobs: 33021, trendPct: 31.9 },
      { name: "Security", jobs: 2306, trendPct: 25.9 },
      { name: "Front-End", jobs: 2719, trendPct: 18.1 },
      { name: "QA", jobs: 3456, trendPct: 13.1 },
      { name: "DevOps", jobs: 1284, trendPct: -4.0 },
    ],
    source: "https://www.trueup.io/job-category-trends",
    chartSource: "https://trueup.io/trends",
    methodology: "TrueUp tracks open jobs at startups and large tech companies; it is not the entire U.S. labor market.",
  },
  linkedin: {
    asOf: "2026-08-28",
    query: "Software Engineer · New York",
    countLabel: "4,000+ last verified",
    source: "https://www.linkedin.com/jobs/search/?geoId=105080838&keywords=software%20engineer&location=New%20York%2C%20United%20States",
    note: "The exact longitudinal query did not expose a reproducible rounded count on Sep 11. The prior 4,000+ observation is retained rather than substituting a different query or fabricating stability.",
  },
  revelio: {
    asOf: "2026-07 occupation slice / 2026-08 broad release",
    releaseDate: "2026-09-03",
    nextRelease: "2026-10-01",
    occupation: "Computer and Mathematical (SOC 15)",
    employmentThousands: 10021.5,
    employmentChangeMomThousands: -0.6,
    employmentChangeYoyThousands: -39.9,
    jobOpenings: 1686687,
    jobOpeningsMomPct: 2.3,
    jobOpeningsYoyPct: 22.8,
    hiringRatePct: 26.7,
    hiringChangeMomPp: 0.4,
    hiringChangeYoyPp: -0.7,
    attritionRatePct: 26.7,
    attritionChangeMomPp: -0.7,
    attritionChangeYoyPp: -1.9,
    newPostingSalary: 124266,
    salaryChangeMomPct: -0.1685,
    salaryChangeYoyPct: 4.4389,
    broadEmploymentChangeThousands: 36.5,
    broadOpeningsMomPct: -3.0,
    broadHiringRatePct: 19.7,
    broadAttritionRatePct: 19.4,
    source: "https://www.reveliolabs.com/public-labor-statistics",
    note: "The Sep 3 release provides August broad-market measures. The prior SOC15 occupational slice is retained because a directly comparable August SOC15 table was not reproducibly extractable; no occupation-specific values were fabricated.",
  },
  aiLaborTracker: {
    asOf: "2026-08",
    exposedRoleDemandChangePct: -42,
    adoptingFirmHeadcountGrowthPct: 26,
    adoptingFirmSeniorGrowthPct: 32,
    adoptingFirmJuniorGrowthPct: 6,
    withinJobActivityChangePct: 87,
    postingsPerHire: 5.81,
    postingsPerHireYoyPct: 264,
    adoptionPaceFromPeakPct: -39,
    source: "https://www.reveliolabs.com/ai-labor-market-tracker",
    note: "The latest tracker strengthens the restructuring interpretation: most measured change remains within jobs, senior headcount at adopters is growing much faster than junior headcount, and matching frictions remain high. The -42 exposure-demand figure is the prior comparable exposure estimate and is retained for context.",
  },
  marketDetails: {
    overallPostings: { value: 102.41, asOf: "2026-09-04" },
    seniority: {
      seniorSharePct: 69.3,
      midChangePct: -6.7,
      seniorChangePct: 13.5,
      comparison: "Change since January 2025",
      source: "Indeed Hiring Lab seniority analysis",
      note: "No newer directly comparable Indeed seniority release was found; retained as the latest stable published baseline.",
    },
    linkedinSeniority: {
      entry: 525,
      associate: 159,
      midSenior: 3490,
      anyTime: 4978,
      pastMonth: 3986,
      pastWeek: 1489,
      pastDay: 370,
      asOf: "2026-08-14",
      note: "No reliable fresh exact-query filter counts were publicly exposed this refresh, so the prior snapshot is retained rather than fabricated.",
    },
    bls: {
      growthPct: 15.8,
      jobsAdded: 267700,
      period: "2024–2034",
      source: "https://www.bls.gov/opub/ted/2026/artificial-intelligence-information-technology-and-employment-2024-34.htm",
    },
  },
  personalRisk: {
    level: "Low–Moderate",
    trend: "Stable",
    confidence: "Medium",
    accessibilityRatePct: 66.7,
    sampleSize: 9,
    uniqueEmployers: 8,
    medianMinimumYoe: 5,
    shareMin5PlusPct: 66.7,
    shareMin7PlusPct: 22.2,
    shareMin10PlusPct: 0,
    experienceInflation: "Mild upward signal, not a NYC-specific cliff: Revelio's 75M-tech-posting analysis says average required experience per skill rose about 4%, from roughly 4.6 to 4.8 years since 2024, while average skill breadth fell from about 30 to 21. That points to deeper specialization rather than a categorical shift beyond 5 YOE.",
    bands: [
      { band: "0–2", count: 2 },
      { band: "3–4", count: 1 },
      { band: "5–6", count: 4 },
      { band: "7–9", count: 2 },
      { band: "10+", count: 0 },
    ],
    sample: [
      { company: "Google", role: "Software Engineer III, Full Stack", minYoe: 2, maxYoe: null, comp: "Not stored", specialty: "Full stack", source: "https://www.linkedin.com/jobs/view/software-engineer-iii-full-stack-at-google-4277393840" },
      { company: "Google", role: "Software Engineer III, Security/Privacy", minYoe: 2, maxYoe: null, comp: "Not stored", specialty: "Security", source: "https://www.linkedin.com/jobs/view/software-engineer-iii-security-privacy-at-google-4280175152" },
      { company: "Interactive Brokers", role: "Software Engineer III", minYoe: 3, maxYoe: null, comp: "Not stored", specialty: "Backend / brokerage", source: "https://www.linkedin.com/jobs/view/software-engineer-iii-at-interactive-brokers-4272289443" },
      { company: "Harvey", role: "Senior Software Engineer, Backend", minYoe: 5, maxYoe: null, comp: "$193.4k–$290k", specialty: "Backend", source: "https://www.linkedin.com/jobs/view/senior-software-engineer-backend-at-harvey-4262908755" },
      { company: "Amazon", role: "Machine Learning Infrastructure Engineer, Fauna", minYoe: 5, maxYoe: null, comp: "Not stored", specialty: "ML infrastructure", source: "https://www.linkedin.com/jobs/view/machine-learning-infrastructure-engineer-fauna-at-amazon-4271696996" },
      { company: "Plaid", role: "Senior Software Engineer, ML Infrastructure", minYoe: 5, maxYoe: null, comp: "$190.8k–$286.8k", specialty: "ML infrastructure", source: "https://www.linkedin.com/jobs/view/senior-software-engineer-ml-infrastructure-at-plaid-4270694289" },
      { company: "Snap", role: "Software Engineer, Backend, Level 5", minYoe: 6, maxYoe: null, comp: "Not stored", specialty: "Distributed backend", source: "https://www.linkedin.com/jobs/view/software-engineer-backend-level-5-at-snap-inc-4278964520" },
      { company: "Fubo", role: "Senior Backend Software Engineer", minYoe: 7, maxYoe: null, comp: "Not stored", specialty: "Cloud backend", source: "https://www.linkedin.com/jobs/view/senior-backend-software-engineer-at-fubo-4273194134" },
      { company: "Cypress Group", role: "Senior Backend Engineer", minYoe: 7, maxYoe: 10, comp: "$180k–$240k", specialty: "Backend", source: "https://www.linkedin.com/jobs/view/senior-backend-engineer-at-cypress-group-4266280033" },
    ],
    caveat: "The explicit-YOE headline remains the Aug 28 reproducible baseline because a methodologically comparable sample could not be rerun from the same public surface on Sep 11. Fresh public roles continue to include multiple 4–5 YOE requirements, but those were not substituted into the longitudinal statistic using a different sampling method.",
  },
  replacementEvidence: {
    signal: "Yellow",
    trend: "Stable yellow",
    confidence: "Medium",
    verdict: "AI is materially changing engineering productivity and some hiring/team-size decisions, but broad experienced-SWE replacement is still not established.",
    items: [
      { company: "Stanford DEL", status: "Green", evidence: "No comparable employment decline among experienced workers in highly AI-exposed occupations; the strongest gap remains ages 22–25 and is primarily a hiring effect.", confidence: "High", source: "https://digitaleconomy.stanford.edu/project/indicators/canaries-dashboard/" },
      { company: "Revelio", status: "Green", evidence: "The August tracker finds 87% of measured work-content change within jobs, while AI-adopting firms show senior headcount growth of 32% versus 6% for junior workers. This is inconsistent with broad current displacement of experienced workers.", confidence: "High", source: "https://www.reveliolabs.com/ai-labor-market-tracker" },
      { company: "Meta", status: "Yellow", evidence: "Project OT targeted major AI-linked team reductions, but a planned second wave was reversed after internal evidence showed the AI tooling had not met productivity expectations and technical disruptions increased.", confidence: "High", source: "https://www.reuters.com/technology/artificial-intelligence/meta-scaled-back-ai-driven-job-cuts-after-productivity-concerns-sources-say-2026-08-26/" },
      { company: "Wipro", status: "Yellow", evidence: "Wipro says AI has freed capacity equivalent to about 20,000 workers, but reports redeploying that capacity rather than eliminating those workers and is expanding forward-deployed engineering. This is strong productivity pressure without direct experienced-worker displacement.", confidence: "High", source: "https://www.reuters.com/business/world-at-work/wipro-says-ai-has-freed-capacity-equivalent-20000-workers-2026-09-10/" },
      { company: "Salesforce", status: "Yellow", evidence: "Marc Benioff has attributed roughly flat engineering headcount over about two years partly to AI coding-agent efficiency. This is direct executive attribution but lacks a public engineer-output/headcount causal decomposition.", confidence: "Medium", source: "https://fortune.com/2026/05/28/salesforce-ceo-marc-benioff-ai-engineers-hiring/" },
      { company: "Equifax", status: "Yellow", evidence: "Official filings describe thousands of engineers using AI coding and higher software output/quality from the same engineering investment. This is strong productivity evidence, not evidence of experienced-engineer displacement by itself.", confidence: "High", source: "https://www.sec.gov/Archives/edgar/data/33185/000003318526000011/efx-20251231.htm" },
    ],
  },
  benchmarks: [
    { model: "GPT-6 Astra", score: 74, cost: "$6.52", note: "DeepSWE v1.1 · Sep 3" },
    { model: "Gemini 3.8 Flash", score: 74, cost: "$2.36", note: "DeepSWE v1.1 · Sep 3" },
    { model: "Claude Opus 5", score: 74, cost: "$11.84", note: "DeepSWE v1.1 · Sep 3" },
    { model: "GPT-5.6 Sol", score: 73, cost: "$6.46", note: "DeepSWE v1.1" },
    { model: "Claude Fable 5", score: 70, cost: "$13.41", note: "DeepSWE v1.1" },
    { model: "GLM-5.3", score: 69, cost: "$3.99", note: "DeepSWE v1.1" },
    { model: "Kimi K3", score: 69, cost: "$4.65", note: "DeepSWE v1.1" },
  ],
  signals: [
    { signal: "Early-career SWE employment", reading: "19% below counterfactual", direction: "Negative", interpretation: "Leading canary, but not the main personal-risk signal at ~5 YOE. Stanford's revised analysis says the effect is concentrated in ages 22–25 and largely reflects reduced hiring.", source: "https://digitaleconomy.stanford.edu/project/indicators/canaries-dashboard/" },
    { signal: "Experienced-worker employment", reading: "No comparable Stanford gap", direction: "Stable", interpretation: "High-quality labor evidence still does not show a broad AI-linked employment gap among experienced workers; Revelio's adopter data also show much stronger senior than junior headcount growth.", source: "https://digitaleconomy.stanford.edu/project/indicators/canaries-dashboard/" },
    { signal: "Automation vs augmentation", reading: "Automation-heavy occupations weaker", direction: "Watch", interpretation: "How AI is deployed remains more informative than exposure alone; augmentation-heavy work has held up better, particularly for experienced workers.", source: "https://digitaleconomy.stanford.edu/project/indicators/canaries-dashboard/" },
    { signal: "AI labor reallocation", reading: "87% of measured change within jobs", direction: "Restructuring", interpretation: "Revelio's August tracker supports job-content change as the dominant current mechanism; senior headcount growth at AI adopters is materially stronger than junior growth.", source: "https://www.reveliolabs.com/ai-labor-market-tracker" },
    { signal: "METR public frontier", reading: "~12h 50%; ~1.5h 80%", direction: "Improving", interpretation: "Strong capability growth, but public evidence still does not demonstrate reliable low-intervention multi-day production ownership; METR warns estimates above 16h are unreliable.", source: "https://metr.org/blog/2026-05-19-frontier-risk-report/" },
    { signal: "Benchmark frontier", reading: "DeepSWE ceiling 74%; Terminal-Bench 87.4%", direction: "Improving", interpretation: "Agent capability broadened and Terminal-Bench advanced materially, but the harder DeepSWE ceiling did not move above 74%. Treat this as capability pressure, not labor-displacement proof.", source: "https://deepswe.datacurve.ai/" },
  ],
  pivotRadar: [
    { area: "AI / ML systems infrastructure", status: "Rising", evidence: "TrueUp ML software +74.2% and DS/ML category +90.1%; the specialization shift favors Python, AI, cloud deployment and ML skills over broad application-development mentions.", fit: "High", track: "NYC ML platform/inference/training infra counts, YOE, comp and employer breadth." },
    { area: "Distributed systems / SRE / networking", status: "Rising", evidence: "TrueUp SRE +53.3% and networking +40.4%, materially stronger than front-end/QA and directly transferable from backend/platform SWE.", fit: "High", track: "Platform, SRE, distributed workflow, cloud and networking demand versus generalist SWE." },
    { area: "Security engineering", status: "Durable / rising", evidence: "TrueUp software-security openings +25.9%; security remains a systems-heavy specialty with meaningful transferability from backend/platform work.", fit: "Medium-high", track: "Security engineering counts, YOE requirements, compensation and AI-security share." },
    { area: "Sales engineering / FDE", status: "Rising", evidence: "TrueUp Sales Engineering +66.7%; Cognizant is actively hiring AI Forward Deployed Engineers around a 5+ YOE profile, and Wipro says it is expanding forward-deployed engineering as AI frees delivery capacity.", fit: "Medium-high", track: "NYC FDE/Solutions/Sales Engineering counts, technical depth and compensation." },
    { area: "Trading / market infrastructure", status: "Strong selective niche", evidence: "NYC continues to expose quant-dev, eTrading and C++ infrastructure openings, but no reliable aggregate biweekly series yet proves acceleration.", fit: "High", track: "Quant dev, eTrading, market data, execution and trading-systems openings by company and YOE." },
  ],
  jobs: [],
  history: [
    { date: "2026-08-14", sweHiring: 74.56, hiringDate: "2026-07-10", trueupSoftwareJobs: 54747, trueupDate: "2026-06-30", linkedinNycSwe: "4,000+", earlyCareerChange: "≈ -20%", deepSweBest: 74, deepSweLeader: "Claude Opus 5", metrHorizon: "~12h" },
    { date: "2026-08-28", sweHiring: 74.57, hiringDate: "2026-08-21", overallHiring: 101.91, trueupSoftwareJobs: 54747, trueupDate: "2026-07-31", linkedinNycSwe: "4,000+", earlyCareerChange: "-19%", experiencedWorkerGap: "No comparable decline", fiveYoeAccessibilityPct: 66.7, explicitYoeSampleN: 9, replacementSignal: "Yellow", deepSweBest: 74, deepSweLeader: "Claude Opus 5", metrHorizon: "~12h" },
    { date: "2026-09-11", sweHiring: 76.12, hiringDate: "2026-09-04", overallHiring: 102.41, trueupSoftwareJobs: 54747, trueupDate: "2026-08-31", linkedinNycSwe: "4,000+ last verified 2026-08-28", earlyCareerChange: "-19%", experiencedWorkerGap: "No comparable decline", fiveYoeAccessibilityPct: 66.7, explicitYoeSampleN: 9, replacementSignal: "Yellow", deepSweBest: 74, deepSweLeader: "GPT-6 Astra / Gemini 3.8 Flash / Claude Opus 5", terminalBenchBest: 87.4, terminalBenchLeader: "GPT-6 Astra + Codex", metrHorizon: "~12h" },
  ],
  sources: [
    ["SWE hiring", "FRED / Indeed", "https://fred.stlouisfed.org/series/IHLIDXUSTPSOFTDEVE"],
    ["Overall hiring", "FRED / Indeed", "https://fred.stlouisfed.org/series/IHLIDXUS"],
    ["Tech/SWE openings", "TrueUp", "https://www.trueup.io/job-category-trends"],
    ["NY software jobs", "LinkedIn", "https://www.linkedin.com/jobs/search/?geoId=105080838&keywords=software%20engineer&location=New%20York%2C%20United%20States"],
    ["Labor displacement", "Stanford Digital Economy Lab", "https://digitaleconomy.stanford.edu/project/indicators/canaries-dashboard/"],
    ["Worker flows", "Revelio Public Labor Statistics", "https://www.reveliolabs.com/public-labor-statistics"],
    ["AI labor changes", "Revelio AI Labor Market Tracker", "https://www.reveliolabs.com/ai-labor-market-tracker"],
    ["Tech specialization", "Revelio Labs", "https://www.reveliolabs.com/news/business/tech-hiring-is-getting-more-specialized/"],
    ["Autonomous task horizon", "METR", "https://metr.org/time-horizons/"],
    ["Hard coding benchmark", "DeepSWE", "https://deepswe.datacurve.ai/"],
    ["Agent benchmark", "Terminal-Bench 2.1", "https://www.tbench.ai/leaderboard/terminal-bench/2.1"],
  ],
} as const;

export const sourceArchitecture = [
  { source: "Indeed/FRED + LinkedIn + TrueUp", role: "Core repeatable demand layer", availability: "Active", confidence: "High for FRED; medium for repeated public LinkedIn; medium-high for TrueUp within its tech-company universe", use: "Posting levels, direction, seniority and NYC demand.", limit: "Never combine counts into one census.", url: "https://fred.stlouisfed.org/series/IHLIDXUSTPSOFTDEVE" },
  { source: "Lightcast", role: "Optional granular postings layer", availability: "Public aggregate reports available; licensed microdata/API not available", confidence: "Medium for public aggregates; no microdata claims", use: "Public aggregate trend/skills context; future YOE and persistence only if free/public microdata becomes accessible.", limit: "Do not imply paid API access.", url: "https://lightcast.io/resources/blog/is-ai-the-end-for-software-engineering" },
  { source: "Revelio + Stanford + BLS", role: "Actual-worker, hiring, attrition and structural layer", availability: "Active on each source's release cadence", confidence: "High when directly applicable", use: "Separate posting weakness from actual employment and AI-linked displacement.", limit: "Revelio SOC15 and BLS are broader/slower than SWE-specific biweekly postings.", url: "https://www.reveliolabs.com/public-labor-statistics" },
  { source: "SEC/company disclosures + Reuters", role: "Experienced-SWE substitution evidence gate", availability: "Event-driven", confidence: "High for filings and corroborated reporting; medium for executive attribution alone", use: "Headcount, output, backfills and explicit AI attribution.", limit: "Productivity alone is not displacement.", url: "https://www.sec.gov/edgar/search/" },
  { source: "New York WARN", role: "NYC layoff shock control", availability: "Active public watch", confidence: "High for covered events; low for occupation/AI specificity", use: "Check whether NYC deterioration is concentrated in specific mass layoffs.", limit: "WARN does not identify SWE composition reliably.", url: "https://dol.ny.gov/warn-dashboard" },
] as const;

export const longitudinalMethod = [
  "Append each dated observation; never overwrite earlier snapshots.",
  "Show 2-week, 4-week, 12-week, and year-over-year movement only after enough comparable observations exist.",
  "Classify weak-but-improving separately from weak-and-deteriorating; flag structural breaks only when moves exceed recent noise or multiple sources corroborate.",
  "Treat missing or inaccessible data as unavailable, never as zero or stable.",
  "Keep NYC separate from national data, literal YOE separate from platform seniority labels, and labor outcomes separate from AI capability benchmarks.",
] as const;
