export const dashboardData = {
  updatedAt: "2026-08-28",
  nextRefresh: "2026-09-11",
  cadence: "Every 2 weeks",
  currentRead: "SWE hiring remains weak but is not currently deteriorating. The clearest labor damage is still concentrated in early-career hiring, not experienced engineers. Company-level AI substitution attempts are real enough to move the experienced-replacement signal to yellow, but current evidence does not support a serious pivot out of SWE for a competent engineer around 5 YOE.",
  overview: {
    personalRisk: "Low–Moderate",
    personalRiskTrend: "Stable",
    personalRiskConfidence: "Medium",
    hiring: "Weak, roughly flat",
    hiringTrend: "Stable",
    aiReplacement: "Yellow / watch",
    aiReplacementTrend: "Up from green",
    midLevel: "Weak / senior-skewed",
    senior: "Stronger",
    nycDemand: "Stable at 4,000+ on the same LinkedIn query",
    pivot: "No pivot signal",
    pivotDistance: "Three of four pivot gates are not met; one is partially met through company-specific AI-linked hiring/cut evidence.",
    changed: [
      "Indeed SWE postings edged up over the latest two weeks, but remain about 27 index points below overall U.S. postings.",
      "Stanford's August revision still finds no comparable AI-linked employment gap among experienced workers; the 22–25 gap is now 19% and appears driven mainly by reduced hiring.",
      "Experienced-replacement evidence moved from green to yellow: Meta attempted major AI-linked team reductions but reversed a planned second wave after internal productivity/reliability problems; Salesforce continues to describe flat engineering headcount as an AI-efficiency effect.",
      "The first explicit-YOE NYC sample puts the median minimum at 5 years; 6 of 9 sampled roles are accessible at 5 YOE. This is a baseline, not yet a trend.",
      "Frontier capability did not show a new discontinuity: DeepSWE's leader remains 74%, and METR's public long-horizon evidence is unchanged.",
    ],
  },
  metrics: [
    { label: "Indeed/FRED SWE hiring", value: "74.57", note: "Aug 21, 2026 · Feb 2020 = 100", tone: "negative" },
    { label: "TrueUp software jobs", value: "54,747", note: "Jul 31, 2026 · +34.1% on TrueUp trend measure", tone: "positive" },
    { label: "LinkedIn NY SWE", value: "4,000+", note: "Same public New York query · Aug 28", tone: "neutral" },
    { label: "Early-career AI gap", value: "-19%", note: "Ages 22–25 in highly AI-exposed occupations · Stanford Aug revision", tone: "negative" },
    { label: "DeepSWE frontier", value: "74%", note: "Claude Opus 5 · leaderboard updated Aug 26", tone: "neutral" },
    { label: "METR 50% horizon", value: "~12 h", note: "Public frontier · Feb–Mar 2026 · high uncertainty above 16h", tone: "neutral" },
  ],
  trends: {
    swe: {
      current: 74.57,
      asOf: "2026-08-21",
      twoWeekPct: 1.24,
      fourWeekPct: -1.21,
      twelveWeekPct: null,
      yoyPct: null,
      direction: "Flat",
      velocity: "Stable",
      structuralBreak: false,
      note: "Weak level, but no new downward break. Two-week improvement is small relative to the persistent post-2022 decline.",
    },
    overall: {
      current: 101.91,
      asOf: "2026-08-21",
      twoWeekPct: null,
      fourWeekPct: null,
      twelveWeekPct: null,
      yoyPct: null,
      direction: "Flat",
      velocity: "Stable",
    },
    relativeGapPoints: -27.34,
    relativeGapPct: -26.83,
  },
  trueup: {
    asOf: "2026-07-31",
    totalTechJobs: 262300,
    categoryTotal: 216625,
    softwareJobs: 54747,
    softwareTrendPct: 34.1,
    categories: [
      { name: "Data Science & ML", jobs: 9075, trendPct: 90.1 },
      { name: "Sales Engineering", jobs: 6231, trendPct: 66.7 },
      { name: "Business Ops / Program Mgmt", jobs: 16555, trendPct: 43.6 },
      { name: "Software Engineering", jobs: 54747, trendPct: 34.1 },
      { name: "Research", jobs: 1695, trendPct: 28.4 },
      { name: "Product Management", jobs: 5752, trendPct: 27.2 },
      { name: "IT & Business Systems", jobs: 8312, trendPct: 22.0 },
      { name: "Hardware Engineering", jobs: 4004, trendPct: 14.4 },
    ],
    softwareSubcategories: [
      { name: "Machine Learning", jobs: 4153, trendPct: 74.2 },
      { name: "Site Reliability Engineering", jobs: 1712, trendPct: 53.3 },
      { name: "Data", jobs: 4095, trendPct: 51.2 },
      { name: "Networking", jobs: 1028, trendPct: 40.4 },
      { name: "Generalist", jobs: 33021, trendPct: 31.9 },
      { name: "Security", jobs: 2306, trendPct: 25.9 },
      { name: "Front-End", jobs: 2719, trendPct: 18.1 },
      { name: "QA", jobs: 3456, trendPct: 13.1 },
    ],
    source: "https://www.trueup.io/job-category-trends",
    chartSource: "https://trueup.io/trends",
    methodology: "TrueUp tracks open jobs at startups and large tech companies; it is not the entire U.S. labor market.",
  },
  linkedin: {
    asOf: "2026-08-28",
    query: "Software Engineer · New York",
    countLabel: "4,000+",
    source: "https://www.linkedin.com/jobs/search/?geoId=105080838&keywords=software%20engineer&location=New%20York%2C%20United%20States",
    note: "The same public query remains at the rounded 4,000+ bucket. Other LinkedIn geography/query variants expose larger counts and are not substituted into this longitudinal series.",
  },
  revelio: {
    asOf: "2026-07",
    releaseDate: "2026-08-06",
    nextRelease: "2026-09-03",
    occupation: "Computer and Mathematical (SOC 15)",
    employmentThousands: 10021.5,
    employmentChangeMomThousands: -0.6,
    employmentChangeYoyThousands: -39.9,
    jobOpenings: 1686687,
    jobOpeningsMomPct: 2.3,
    jobOpeningsYoyPct: 22.8,
    hiringRatePct: 26.7,
    hiringChangeMomPp: 0.4,
    hiringChangeYoyPp: -0.7,
    attritionRatePct: 26.7,
    attritionChangeMomPp: -0.7,
    attritionChangeYoyPp: -1.9,
    newPostingSalary: 124266,
    salaryChangeMomPct: -0.1685,
    salaryChangeYoyPct: 4.4389,
    source: "https://www.reveliolabs.com/public-labor-statistics",
    note: "No newer public monthly release exists yet. SOC 15 is broader than software engineering and is not YOE-specific.",
  },
  aiLaborTracker: {
    asOf: "2026-07",
    exposedRoleDemandChangePct: -42,
    adoptingFirmHeadcountGrowthPct: 27,
    withinJobActivityChangePct: 93,
    postingsPerHire: 5.05,
    postingsPerHireYoyPct: 264,
    source: "https://www.reveliolabs.com/ai-labor-market-tracker",
    note: "Broad AI-exposure/adoption measures, not experienced-SWE-specific. Useful for causality context, not a personal-risk estimate.",
  },
  marketDetails: {
    overallPostings: { value: 101.91, asOf: "2026-08-21" },
    seniority: {
      seniorSharePct: 69.3,
      midChangePct: -6.7,
      seniorChangePct: 13.5,
      comparison: "Change since January 2025",
      source: "Indeed Hiring Lab seniority analysis",
      note: "No newer comparable seniority release found this refresh; retained as the latest stable published baseline.",
    },
    linkedinSeniority: {
      entry: 525,
      associate: 159,
      midSenior: 3490,
      anyTime: 4978,
      pastMonth: 3986,
      pastWeek: 1489,
      pastDay: 370,
      asOf: "2026-08-14",
      note: "No reliable fresh exact-query filter counts were exposed publicly on Aug 28, so the prior snapshot is retained rather than fabricated.",
    },
    bls: {
      growthPct: 15.8,
      jobsAdded: 267700,
      period: "2024–2034",
      source: "https://www.bls.gov/opub/ted/2026/artificial-intelligence-information-technology-and-employment-2024-34.htm",
    },
  },
  personalRisk: {
    level: "Low–Moderate",
    trend: "Stable",
    confidence: "Medium",
    accessibilityRatePct: 66.7,
    sampleSize: 9,
    uniqueEmployers: 8,
    medianMinimumYoe: 5,
    shareMin5PlusPct: 66.7,
    shareMin7PlusPct: 22.2,
    shareMin10PlusPct: 0,
    experienceInflation: "Baseline only — no prior explicit-YOE sample exists yet, so a trend cannot be claimed.",
    bands: [
      { band: "0–2", count: 2 },
      { band: "3–4", count: 1 },
      { band: "5–6", count: 4 },
      { band: "7–9", count: 2 },
      { band: "10+", count: 0 },
    ],
    sample: [
      { company: "Google", role: "Software Engineer III, Full Stack", minYoe: 2, maxYoe: null, comp: "Not stored", specialty: "Full stack", source: "https://www.linkedin.com/jobs/view/software-engineer-iii-full-stack-at-google-4277393840" },
      { company: "Google", role: "Software Engineer III, Security/Privacy", minYoe: 2, maxYoe: null, comp: "Not stored", specialty: "Security", source: "https://www.linkedin.com/jobs/view/software-engineer-iii-security-privacy-at-google-4280175152" },
      { company: "Interactive Brokers", role: "Software Engineer III", minYoe: 3, maxYoe: null, comp: "Not stored", specialty: "Backend / brokerage", source: "https://www.linkedin.com/jobs/view/software-engineer-iii-at-interactive-brokers-4272289443" },
      { company: "Harvey", role: "Senior Software Engineer, Backend", minYoe: 5, maxYoe: null, comp: "$193.4k–$290k", specialty: "Backend", source: "https://www.linkedin.com/jobs/view/senior-software-engineer-backend-at-harvey-4262908755" },
      { company: "Amazon", role: "Machine Learning Infrastructure Engineer, Fauna", minYoe: 5, maxYoe: null, comp: "Not stored", specialty: "ML infrastructure", source: "https://www.linkedin.com/jobs/view/machine-learning-infrastructure-engineer-fauna-at-amazon-4271696996" },
      { company: "Plaid", role: "Senior Software Engineer, ML Infrastructure", minYoe: 5, maxYoe: null, comp: "$190.8k–$286.8k", specialty: "ML infrastructure", source: "https://www.linkedin.com/jobs/view/senior-software-engineer-ml-infrastructure-at-plaid-4270694289" },
      { company: "Snap", role: "Software Engineer, Backend, Level 5", minYoe: 6, maxYoe: null, comp: "Not stored", specialty: "Distributed backend", source: "https://www.linkedin.com/jobs/view/software-engineer-backend-level-5-at-snap-inc-4278964520" },
      { company: "Fubo", role: "Senior Backend Software Engineer", minYoe: 7, maxYoe: null, comp: "Not stored", specialty: "Cloud backend", source: "https://www.linkedin.com/jobs/view/senior-backend-software-engineer-at-fubo-4273194134" },
      { company: "Cypress Group", role: "Senior Backend Engineer", minYoe: 7, maxYoe: 10, comp: "$180k–$240k", specialty: "Backend", source: "https://www.linkedin.com/jobs/view/senior-backend-engineer-at-cypress-group-4266280033" },
    ],
    caveat: "Small, intentionally inspectable sample biased toward mid/senior public postings. The 66.7% accessibility rate is a baseline for repeated sampling, not an estimate of all NYC SWE jobs.",
  },
  replacementEvidence: {
    signal: "Yellow",
    trend: "Strengthened from green",
    confidence: "Medium",
    verdict: "AI is affecting engineering hiring and team-size decisions at some firms, but broad experienced-SWE replacement is not established.",
    items: [
      { company: "Stanford DEL", status: "Green", evidence: "No comparable employment decline among experienced workers in highly AI-exposed occupations; the strongest gap remains ages 22–25 and is primarily a hiring effect.", confidence: "High", source: "https://digitaleconomy.stanford.edu/project/indicators/canaries-dashboard/" },
      { company: "Meta", status: "Yellow", evidence: "Project OT targeted major AI-linked team reductions, but a planned second wave was reversed after internal evidence showed the AI tooling had not met productivity expectations and technical disruptions increased.", confidence: "High", source: "https://www.reuters.com/technology/artificial-intelligence/meta-scaled-back-ai-driven-job-cuts-after-productivity-concerns-sources-say-2026-08-26/" },
      { company: "Salesforce", status: "Yellow", evidence: "Marc Benioff has attributed roughly flat engineering headcount over about two years partly to AI coding-agent efficiency. This is direct executive attribution but lacks a public engineer-output/headcount causal decomposition.", confidence: "Medium", source: "https://fortune.com/2026/05/28/salesforce-ceo-marc-benioff-ai-engineers-hiring/" },
      { company: "Equifax", status: "Yellow", evidence: "Official filings describe thousands of engineers using AI coding and higher software output/quality from the same engineering investment. This is strong productivity evidence, not evidence of experienced-engineer displacement by itself.", confidence: "High", source: "https://www.sec.gov/Archives/edgar/data/33185/000003318526000011/efx-20251231.htm" },
    ],
  },
  benchmarks: [
    { model: "Claude Opus 5", score: 74, cost: "$11.84", note: "DeepSWE v1.1 · Aug 26" },
    { model: "GPT-5.6 Sol", score: 73, cost: "$6.46", note: "DeepSWE v1.1 · Aug 26" },
    { model: "Claude Fable 5", score: 70, cost: "$21.63", note: "DeepSWE v1.1" },
    { model: "GLM-5.3", score: 69, cost: "$3.99", note: "DeepSWE v1.1" },
    { model: "Kimi K3", score: 69, cost: "—", note: "DeepSWE v1.1" },
    { model: "GPT-5.6 Luna", score: 67, cost: "—", note: "DeepSWE v1.1" },
    { model: "GPT-5.5", score: 67, cost: "—", note: "DeepSWE v1.1" },
  ],
  signals: [
    { signal: "Early-career SWE employment", reading: "19% below counterfactual", direction: "Negative", interpretation: "Leading canary, but not the main personal-risk signal at ~5 YOE. Stanford's revised analysis says the effect is concentrated in ages 22–25 and largely reflects reduced hiring.", source: "https://digitaleconomy.stanford.edu/project/indicators/canaries-dashboard/" },
    { signal: "Experienced-worker employment", reading: "No comparable decline", direction: "Stable", interpretation: "Current high-quality labor evidence still does not show a broad AI-linked employment gap among experienced workers.", source: "https://digitaleconomy.stanford.edu/project/indicators/canaries-dashboard/" },
    { signal: "Automation vs augmentation", reading: "Automation-heavy occupations weaker", direction: "Watch", interpretation: "How AI is deployed remains more informative than exposure alone; augmentation-heavy work has held up better.", source: "https://digitaleconomy.stanford.edu/project/indicators/canaries-dashboard/" },
    { signal: "AI labor reallocation", reading: "93% of measured activity change within jobs", direction: "Restructuring", interpretation: "Revelio's tracker supports job-content change as the dominant current mechanism rather than wholesale occupational replacement.", source: "https://www.reveliolabs.com/ai-labor-market-tracker" },
    { signal: "METR public frontier", reading: "~12h 50%; ~1.5h 80%", direction: "Improving", interpretation: "Strong capability growth, but public evidence still does not demonstrate reliable low-intervention multi-day production ownership; METR warns estimates above 16h are unreliable.", source: "https://metr.org/blog/2026-05-19-frontier-risk-report/" },
    { signal: "Benchmark frontier", reading: "DeepSWE leader unchanged at 74%", direction: "Flat", interpretation: "No new benchmark discontinuity this cycle. Capability remains high but did not jump enough to change the labor conclusion.", source: "https://deepswe.datacurve.ai/" },
  ],
  pivotRadar: [
    { area: "AI / ML systems infrastructure", status: "Rising", evidence: "TrueUp ML software +74.2% and DS/ML category +90.1%; strong NYC role overlap with backend/distributed-systems skills.", fit: "High", track: "NYC ML platform/inference/training infra counts, YOE, comp and employer breadth." },
    { area: "Distributed systems / SRE / networking", status: "Rising", evidence: "TrueUp SRE +53.3% and networking +40.4%, materially stronger than front-end/QA and directly transferable from backend/platform SWE.", fit: "High", track: "Platform, SRE, distributed workflow, cloud and networking demand versus generalist SWE." },
    { area: "Security engineering", status: "Durable / rising", evidence: "TrueUp software-security openings +25.9%; current NYC postings include security/privacy and AI-security roles.", fit: "Medium-high", track: "Security engineering counts, YOE requirements, compensation and AI-security share." },
    { area: "Sales engineering / FDE", status: "Rising", evidence: "TrueUp Sales Engineering +66.7%; demand benefits from enterprise AI deployment, but role content and compensation vary more than core platform engineering.", fit: "Medium-high", track: "NYC FDE/Solutions/Sales Engineering counts, technical depth and compensation." },
    { area: "Trading / market infrastructure", status: "Strong selective niche", evidence: "NYC continues to expose quant-dev, eTrading and C++ infrastructure openings, but no reliable aggregate biweekly series yet proves acceleration.", fit: "High", track: "Quant dev, eTrading, market data, execution and trading-systems openings by company and YOE." },
  ],
  jobs: [],
  history: [
    { date: "2026-08-14", sweHiring: 74.56, hiringDate: "2026-07-10", trueupSoftwareJobs: 54747, trueupDate: "2026-06-30", linkedinNycSwe: "4,000+", earlyCareerChange: "≈ -20%", deepSweBest: 74, deepSweLeader: "Claude Opus 5", metrHorizon: "~12h" },
    { date: "2026-08-28", sweHiring: 74.57, hiringDate: "2026-08-21", overallHiring: 101.91, trueupSoftwareJobs: 54747, trueupDate: "2026-07-31", linkedinNycSwe: "4,000+", earlyCareerChange: "-19%", experiencedWorkerGap: "No comparable decline", fiveYoeAccessibilityPct: 66.7, explicitYoeSampleN: 9, replacementSignal: "Yellow", deepSweBest: 74, deepSweLeader: "Claude Opus 5", metrHorizon: "~12h" },
  ],
  sources: [
    ["SWE hiring", "FRED / Indeed", "https://fred.stlouisfed.org/series/IHLIDXUSTPSOFTDEVE"],
    ["Overall hiring", "FRED / Indeed", "https://fred.stlouisfed.org/series/IHLIDXUS"],
    ["Tech/SWE openings", "TrueUp", "https://www.trueup.io/job-category-trends"],
    ["NY software jobs", "LinkedIn", "https://www.linkedin.com/jobs/search/?geoId=105080838&keywords=software%20engineer&location=New%20York%2C%20United%20States"],
    ["Labor displacement", "Stanford Digital Economy Lab", "https://digitaleconomy.stanford.edu/project/indicators/canaries-dashboard/"],
    ["Worker flows", "Revelio Public Labor Statistics", "https://www.reveliolabs.com/public-labor-statistics"],
    ["AI labor changes", "Revelio AI Labor Market Tracker", "https://www.reveliolabs.com/ai-labor-market-tracker"],
    ["Autonomous task horizon", "METR", "https://metr.org/time-horizons/"],
    ["Hard coding benchmark", "DeepSWE", "https://deepswe.datacurve.ai/"],
    ["Agent benchmark", "Terminal-Bench 2.1", "https://www.tbench.ai/leaderboard/terminal-bench/2.1"],
  ],
} as const;

export const sourceArchitecture = [
  { source: "Indeed/FRED + LinkedIn + TrueUp", role: "Core repeatable demand layer", availability: "Active", confidence: "High for FRED; medium for repeated public LinkedIn; medium-high for TrueUp within its tech-company universe", use: "Posting levels, direction, seniority and NYC demand.", limit: "Never combine counts into one census.", url: "https://fred.stlouisfed.org/series/IHLIDXUSTPSOFTDEVE" },
  { source: "Lightcast", role: "Optional granular postings layer", availability: "Public aggregate reports available; licensed microdata/API not available", confidence: "Medium for public aggregates; no microdata claims", use: "Public aggregate trend/skills context; future YOE and persistence only if free/public microdata becomes accessible.", limit: "Do not imply paid API access.", url: "https://lightcast.io/resources/blog/is-ai-the-end-for-software-engineering" },
  { source: "Revelio + Stanford + BLS", role: "Actual-worker, hiring, attrition and structural layer", availability: "Active on each source's release cadence", confidence: "High when directly applicable", use: "Separate posting weakness from actual employment and AI-linked displacement.", limit: "Revelio SOC15 and BLS are broader/slower than SWE-specific biweekly postings.", url: "https://www.reveliolabs.com/public-labor-statistics" },
  { source: "SEC/company disclosures + Reuters", role: "Experienced-SWE substitution evidence gate", availability: "Event-driven", confidence: "High for filings and corroborated reporting; medium for executive attribution alone", use: "Headcount, output, backfills and explicit AI attribution.", limit: "Productivity alone is not displacement.", url: "https://www.sec.gov/edgar/search/" },
  { source: "New York WARN", role: "NYC layoff shock control", availability: "Active public watch", confidence: "High for covered events; low for occupation/AI specificity", use: "Check whether NYC deterioration is concentrated in specific mass layoffs.", limit: "WARN does not identify SWE composition reliably.", url: "https://dol.ny.gov/warn-dashboard" },
] as const;

export const longitudinalMethod = [
  "Append each dated observation; never overwrite earlier snapshots.",
  "Show 2-week, 4-week, 12-week, and year-over-year movement only after enough comparable observations exist.",
  "Classify weak-but-improving separately from weak-and-deteriorating; flag structural breaks only when moves exceed recent noise or multiple sources corroborate.",
  "Treat missing or inaccessible data as unavailable, never as zero or stable.",
  "Keep NYC separate from national data, literal YOE separate from platform seniority labels, and labor outcomes separate from AI capability benchmarks.",
] as const;
