import { loadLatestSnapshot } from "../../../lib/market-turso";
import { dashboardData } from "../data";
import styles from "../page.module.css";

export const dynamic = "force-dynamic";

export default async function CareerResponsePage() {
  const d = await loadLatestSnapshot(dashboardData);
  return <main className={styles.page}>
    <header className={styles.top}><div><span className={styles.topKicker}>Career response</span><h1 className={styles.title}>Where demand is moving</h1><p className={styles.dek}>Adjacent paths are ranked by repeated demand evidence, skill overlap and accessibility from an experienced SWE—not by theoretical AI resistance.</p></div><dl className={styles.stamp}><div><dt>Current action</dt><dd>Stay in SWE</dd></div><div><dt>Prepare</dt><dd>Systems-heavy options</dd></div></dl></header>
    <nav className={styles.sectionNav}><a href="/ai-dashboard">Overview</a><a href="/ai-dashboard/personal-risk">Personal risk</a><a href="/ai-dashboard/labor-market">Labor market</a><a href="/ai-dashboard/ai-replacement">AI replacement</a><a href="/ai-dashboard/career-response">Career response</a></nav>
    <section className={styles.readout}><div><span>Current recommendation</span><h2>Do not pivot out of SWE. Bias skill-building toward platform, distributed systems and AI/ML infrastructure.</h2><p>The serious pivot threshold remains unmet. The new specialization data strengthen the case for deeper systems/infra expertise rather than abandoning engineering.</p></div></section>
    <section className={styles.section}><header className={styles.sectionHead}><div><span>01</span><h2>Skill migration</h2></div><p>TrueUp tech-company trends are directional, not a census; Revelio's specialization analysis provides a separate structural check.</p></header><div className={styles.pathCards}>{d.pivotRadar.map((x,i)=><article key={x.area}><span>{String(i+1).padStart(2,"0")}</span><h3>{x.area}</h3><strong>{x.status} · fit {x.fit}</strong><p>{x.evidence}</p></article>)}</div></section>
    <section className={styles.section}><header className={styles.sectionHead}><div><span>02</span><h2>Software subcategories</h2></div><p>Current TrueUp direction as of {d.trueup.asOf}.</p></header><div className={styles.tableWrap}><table className={styles.dataTable}><thead><tr><th>Specialty</th><th>Open jobs</th><th>Trend</th><th>Read</th></tr></thead><tbody>{d.trueup.softwareSubcategories.map(x=><tr key={x.name}><td>{x.name}</td><td>{x.jobs.toLocaleString()}</td><td className={x.trendPct >= 0 ? styles.value : styles.negative}>{x.trendPct >= 0 ? "+" : ""}{x.trendPct}%</td><td>{x.trendPct >= 40 ? "Strong relative momentum" : x.trendPct >= 20 ? "Positive" : x.trendPct >= 0 ? "Positive, slower" : "Negative"}</td></tr>)}</tbody></table></div></section>
    <section className={styles.section}><header className={styles.sectionHead}><div><span>03</span><h2>Pivot threshold</h2></div><p>A serious exit from SWE requires corroboration, not anxiety or one benchmark.</p></header><div className={styles.evidenceList}><article className={styles.up}><div><span>4–10 YOE deterioration vs controls</span><strong>Not met</strong></div><p>Specialization pressure is increasing, but experienced-worker outcomes remain comparatively stable and the SWE posting index improved over the latest 2–4 week windows.</p></article><article className={styles.warning}><div><span>AI-driven experienced headcount substitution</span><strong>Partially met</strong></div><p>Concrete productivity and team-size effects exist, but Meta's reversal, Wipro's redeployment, and Revelio's senior growth data prevent a broad-replacement conclusion.</p></article><article className={styles.up}><div><span>Reliable multi-day autonomous production ownership</span><strong>Not met</strong></div><p>Terminal-Bench improved sharply and the DeepSWE frontier broadened, but public reliability evidence still does not establish sustained low-intervention multi-day ownership of messy production systems.</p></article><article className={styles.up}><div><span>Clearly better adjacent risk-adjusted path</span><strong>Not met</strong></div><p>AI/ML infrastructure, distributed systems/SRE and FDE look stronger than generic application work, but they are mostly engineering specializations rather than reasons to leave SWE.</p></article></div></section>
  </main>;
}
