import { loadLatestSnapshot } from "../../../lib/market-turso";
import { dashboardData } from "../data";
import styles from "../page.module.css";

export const dynamic = "force-dynamic";

export default async function CareerResponsePage() {
  const d = await loadLatestSnapshot(dashboardData);
  return <main className={styles.page}>
    <header className={styles.top}><div><span className={styles.topKicker}>Career response</span><h1 className={styles.title}>Where demand is moving</h1><p className={styles.dek}>Adjacent paths are ranked by repeated demand evidence, skill overlap and accessibility from an experienced SWE—not by theoretical AI resistance.</p></div><dl className={styles.stamp}><div><dt>Current action</dt><dd>Stay in SWE</dd></div><div><dt>Prepare</dt><dd>Systems-heavy options</dd></div></dl></header>
    <nav className={styles.sectionNav}><a href="/ai-dashboard">Overview</a><a href="/ai-dashboard/personal-risk">Personal risk</a><a href="/ai-dashboard/labor-market">Labor market</a><a href="/ai-dashboard/ai-replacement">AI replacement</a><a href="/ai-dashboard/career-response">Career response</a></nav>
    <section className={styles.readout}><div><span>Current recommendation</span><h2>Do not pivot out of SWE. Bias skill-building toward platform, distributed systems and AI/ML infrastructure.</h2><p>The serious pivot threshold remains unmet. The useful response is to move toward specialties whose demand is growing faster than generic application work while preserving SWE optionality.</p></div></section>
    <section className={styles.section}><header className={styles.sectionHead}><div><span>01</span><h2>Skill migration</h2></div><p>TrueUp tech-company trends are directional, not a census.</p></header><div className={styles.pathCards}>{d.pivotRadar.map((x,i)=><article key={x.area}><span>{String(i+1).padStart(2,"0")}</span><h3>{x.area}</h3><strong>{x.status} · fit {x.fit}</strong><p>{x.evidence}</p></article>)}</div></section>
    <section className={styles.section}><header className={styles.sectionHead}><div><span>02</span><h2>Software subcategories</h2></div><p>Current TrueUp direction as of {d.trueup.asOf}.</p></header><div className={styles.tableWrap}><table className={styles.dataTable}><thead><tr><th>Specialty</th><th>Open jobs</th><th>Trend</th><th>Read</th></tr></thead><tbody>{d.trueup.softwareSubcategories.map(x=><tr key={x.name}><td>{x.name}</td><td>{x.jobs.toLocaleString()}</td><td className={styles.value}>+{x.trendPct}%</td><td>{x.trendPct >= 40 ? "Strong relative momentum" : x.trendPct >= 20 ? "Positive" : "Positive, slower"}</td></tr>)}</tbody></table></div></section>
    <section className={styles.section}><header className={styles.sectionHead}><div><span>03</span><h2>Pivot threshold</h2></div><p>A serious exit from SWE requires corroboration, not anxiety or one benchmark.</p></header><div className={styles.evidenceList}><article className={styles.up}><div><span>4–10 YOE deterioration vs controls</span><strong>Not met</strong></div><p>Mid-level demand is weak, but the first explicit-YOE NYC sample does not show a new 5-YOE cliff and experienced-worker labor outcomes remain comparatively stable.</p></article><article className={styles.warning}><div><span>AI-driven experienced headcount substitution</span><strong>Partially met</strong></div><p>Concrete company attempts/hiring suppression exist, but evidence is mixed and includes failed/reversed substitution attempts.</p></article><article className={styles.up}><div><span>Reliable multi-day autonomous production ownership</span><strong>Not met</strong></div><p>Frontier agents remain far stronger than prior years but public reliability evidence does not establish sustained low-intervention ownership.</p></article><article className={styles.up}><div><span>Clearly better adjacent risk-adjusted path</span><strong>Not met</strong></div><p>Several specialties look stronger than generic SWE, but they are mostly SWE specializations rather than reasons to leave engineering.</p></article></div></section>
  </main>;
}
